FROM golang:1.25.8-trixie@sha256:feb29f1d571353e52350efceeabc6a3f6769c249a97d53cbeececc2ec3f7c202 AS build

WORKDIR /app/

COPY ./.git /app/.git
COPY ./avalanchego /app/avalanchego
COPY ./config /app/config

WORKDIR /app/avalanchego/

RUN /app/avalanchego/scripts/build.sh

RUN mkdir -p /app/conf/coston /app/conf/C /app/logs /app/db

WORKDIR /entrypoint
COPY entrypoint/main.go .
RUN go build -ldflags="-s -w" -o /out/entrypoint main.go

FROM gcr.io/distroless/base:nonroot@sha256:e00da4d3bd422820880b080115b3bad24349bef37ed46d68ed0d13e150dc8d67 AS final

USER nonroot

WORKDIR /app

ENV HTTP_HOST=0.0.0.0 \
    HTTP_PORT=9650 \
    STAKING_PORT=9651 \
    PUBLIC_IP= \
    DB_DIR=/app/db \
    DB_TYPE=leveldb \
    BOOTSTRAP_IPS= \
    BOOTSTRAP_IDS= \
    CHAIN_CONFIG_DIR=/app/conf \
    LOG_DIR=/app/logs \
    LOG_LEVEL=info \
    NETWORK_ID=costwo \
    AUTOCONFIGURE_PUBLIC_IP=1 \
    AUTOCONFIGURE_BOOTSTRAP=1 \
    AUTOCONFIGURE_BOOTSTRAP_ENDPOINT=https://coston2-bootstrap.flare.network/ext/info \
    EXTRA_ARGUMENTS="" \
    BOOTSTRAP_BEACON_CONNECTION_TIMEOUT="1m" \
    HTTP_ALLOWED_HOSTS="*"

COPY --from=build --chown=nonroot:nonroot /app/conf /app/conf
COPY --from=build --chown=nonroot:nonroot /app/logs /app/logs
COPY --from=build --chown=nonroot:nonroot /app/db   /app/db

COPY --from=build --chown=nonroot:nonroot /app/avalanchego/build /app/build
COPY --from=build --chown=nonroot:nonroot /out/entrypoint /app/entrypoint

EXPOSE ${STAKING_PORT}
EXPOSE ${HTTP_PORT}

VOLUME [ "${DB_DIR}" ]
VOLUME [ "${LOG_DIR}" ]
VOLUME [ "${CHAIN_CONFIG_DIR}" ]

ENTRYPOINT [ "/app/entrypoint" ]
