import type { LucideIcon } from "lucide-react";
import { Clock3, Inbox, Mail, MessageCircle, Phone, Send, Star, User } from "lucide-react";

export type Conversation = {
  id: number;
  group: "Pinned" | "Today" | "Yesterday";
  name: string;
  subject: string;
  preview: string;
  time: string;
  isUnread: boolean;
  isOnline: boolean;
  unreadCount: number;
  contact: Contact;
  messages: Message[];
};

export type Message = {
  id: number;
  side: "in" | "out";
  text: string;
  time: string;
};

export type Contact = {
  name: string;
  role: string;
  company: string;
  email: string;
  phone: string;
  website: string;
  location: string;
  timezone: string;
  status: string;
  qualifiedAt: string;
  tags: string[];
};

export type NavItem = {
  id: string;
  title: string;
  label?: string;
  icon: LucideIcon;
  isActive: boolean;
};

export type ChannelItem = NavItem;

export type ViewItem = NavItem;

export const navItems: NavItem[] = [
  { id: "inbox", title: "Inbox", label: "24", icon: Inbox, isActive: true },
  { id: "mentions", title: "Mentions", label: "3", icon: Mail, isActive: false },
  { id: "snoozed", title: "Snoozed", icon: Clock3, isActive: false },
  { id: "sent", title: "Sent", icon: Send, isActive: false },
  { id: "all", title: "All conversations", icon: MessageCircle, isActive: false },
  { id: "unassigned", title: "Unassigned", label: "7", icon: User, isActive: false },
];

export const channelItems: ChannelItem[] = [
  { id: "email", title: "Email", label: "18", icon: Mail, isActive: false },
  { id: "chat", title: "Chat", label: "5", icon: MessageCircle, isActive: false },
  { id: "whatsapp", title: "WhatsApp", label: "1", icon: Phone, isActive: false },
  { id: "instagram", title: "Instagram", label: "0", icon: Phone, isActive: false },
  { id: "facebook", title: "Facebook", label: "0", icon: Phone, isActive: false },
  { id: "phone", title: "Phone", label: "0", icon: Phone, isActive: false },
];

export const viewItems: ViewItem[] = [
  { id: "vip", title: "VIP Customers", label: "8", icon: Star, isActive: false },
  { id: "orders", title: "Orders & Returns", label: "6", icon: Inbox, isActive: false },
  { id: "feedback", title: "Product Feedback", label: "2", icon: MessageCircle, isActive: false },
];

export const conversations: Conversation[] = [
  // Pinned
  {
    id: 1,
    group: "Pinned",
    name: "Olivia Rhye",
    subject: "Deployment pipeline failing on staging since last deploy",
    preview: "We're seeing 502 errors after the latest build went out. Rollback didn't help.",
    time: "Just now",
    isUnread: true,
    isOnline: true,
    unreadCount: 4,
    contact: {
      name: "Olivia Rhye",
      role: "Senior DevOps Engineer",
      company: "Railway Systems Inc.",
      email: "olivia.rhye@weblabs.studio",
      phone: "+1 (415) 555-0123",
      website: "railway.co",
      location: "San Francisco, CA, USA",
      timezone: "PDT (UTC-7)",
      status: "Lead",
      qualifiedAt: "Mar 5, 2026",
      tags: ["DevOps", "Enterprise", "P0"],
    },
    messages: [
      {
        id: 101,
        side: "in",
        text: "We're seeing 502s on staging right after the latest build. We rolled back, but the health checks are still red.",
        time: "10 min ago",
      },
      {
        id: 102,
        side: "out",
        text: "Thanks, Olivia. I'm checking the deploy logs and upstream gateway config now.",
        time: "8 min ago",
      },
      {
        id: 103,
        side: "in",
        text: "The weird part is API traffic looks fine, but the web container is failing readiness probes.",
        time: "5 min ago",
      },
      {
        id: 104,
        side: "out",
        text: "Found a mismatch in the staging environment variables. I'm applying the fix and will confirm once the probes recover.",
        time: "3 min ago",
      },
      { id: 105, side: "in", text: "Great. Keep me posted, this is blocking our QA pass.", time: "1 min ago" },
    ],
  },
  {
    id: 2,
    group: "Pinned",
    name: "Phoenix Baker",
    subject: "Refund for order #8823 — double charged",
    preview: "I was billed twice on the 3rd. Can someone look into this and reverse the duplicate?",
    time: "5m",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Phoenix Baker",
      role: "Operations Lead",
      company: "Meridian Retail Group",
      email: "phoenix.baker@weblabs.studio",
      phone: "+1 (312) 555-0184",
      website: "meridianretail.com",
      location: "Chicago, IL, USA",
      timezone: "CDT (UTC-5)",
      status: "Customer",
      qualifiedAt: "Jan 18, 2026",
      tags: ["Billing", "Enterprise"],
    },
    messages: [
      {
        id: 201,
        side: "in",
        text: "I was charged twice for order #8823. One payment cleared on the 3rd and the duplicate posted this morning.",
        time: "5 min ago",
      },
      {
        id: 202,
        side: "out",
        text: "Thanks for flagging it, Phoenix. I can see both transactions and I'm checking which one was attached to the invoice.",
        time: "4 min ago",
      },
      {
        id: 203,
        side: "in",
        text: "Please reverse the duplicate if possible. Our finance team is closing the week today.",
        time: "3 min ago",
      },
      {
        id: 204,
        side: "out",
        text: "The duplicate was a retry from the old payment method. I've started the refund and sent the receipt to your billing email.",
        time: "2 min ago",
      },
      { id: 205, side: "in", text: "Perfect, thanks. I'll let finance know to expect it.", time: "1 min ago" },
    ],
  },
  {
    id: 3,
    group: "Pinned",
    name: "Lana Steiner",
    subject: "Access to analytics dashboard — permissions issue",
    preview: "I'm getting a 403 since the role update yesterday. Tried clearing cache already.",
    time: "8m",
    isUnread: true,
    isOnline: false,
    unreadCount: 2,
    contact: {
      name: "Lana Steiner",
      role: "Data Platform Lead",
      company: "Monsoon Analytics",
      email: "lana.steiner@acme.inc",
      phone: "+91 98765 43210",
      website: "monsoonanalytics.in",
      location: "Bengaluru, India",
      timezone: "IST (UTC+5:30)",
      status: "Qualified",
      qualifiedAt: "Apr 2, 2026",
      tags: ["IAM", "Enterprise", "High Value"],
    },
    messages: [
      {
        id: 301,
        side: "in",
        text: "I'm getting a 403 on the analytics dashboard since yesterday's role update. Clearing cache did not change anything.",
        time: "8 min ago",
      },
      {
        id: 302,
        side: "out",
        text: "Thanks, Lana. I'll compare your new role against the dashboard permission set.",
        time: "7 min ago",
      },
      {
        id: 303,
        side: "in",
        text: "I still have access to exports, just not the dashboard views. Other admins on my team can open them.",
        time: "5 min ago",
      },
      {
        id: 304,
        side: "out",
        text: "Looks like the Analytics Viewer permission was dropped from your custom role. I've reattached it for your workspace.",
        time: "3 min ago",
      },
      { id: 305, side: "in", text: "That fixed it. Thanks for the quick help.", time: "1 min ago" },
    ],
  },
  // Today
  {
    id: 5,
    group: "Today",
    name: "Demi Wilkinson",
    subject: "Sustainability report inquiry",
    preview: "Hi team, I'm looking for the latest ESG disclosure for our upcoming board meeting.",
    time: "10:42 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 5,
    contact: {
      name: "Demi Wilkinson",
      role: "Sustainability Manager",
      company: "BrightFuture Co.",
      email: "demi.wilkinson@weblabs.studio",
      phone: "+1 (415) 555-0189",
      website: "brightfuture.co",
      location: "San Francisco, CA, USA",
      timezone: "PDT (UTC-7)",
      status: "Qualified",
      qualifiedAt: "Jan 22, 2026",
      tags: ["Sustainability", "Enterprise", "FinServ"],
    },
    messages: [
      {
        id: 501,
        side: "in",
        text: "Hi, we're preparing board materials and need your latest ESG disclosure, especially the carbon footprint section.",
        time: "10:42 AM",
      },
      {
        id: 502,
        side: "out",
        text: "Hi Demi. I can share the 2025 report and the carbon accounting appendix. Do you need the raw emissions data too?",
        time: "10:44 AM",
      },
      {
        id: 503,
        side: "in",
        text: "Yes, raw Scope 3 data would help. Our board packet needs supply-chain numbers, not just the summary.",
        time: "10:47 AM",
      },
      {
        id: 504,
        side: "out",
        text: "Got it. I'll send the executive summary, Scope 3 CSV, and the methodology note in one bundle.",
        time: "10:49 AM",
      },
      { id: 505, side: "in", text: "Perfect. That should cover everything for Thursday.", time: "10:50 AM" },
    ],
  },
  {
    id: 6,
    group: "Today",
    name: "Candice Wu",
    subject: "Bulk export keeps timing out",
    preview: "Tried three times this morning. It gets to about 60% then throws a gateway error.",
    time: "10:15 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Candice Wu",
      role: "Data Engineer",
      company: "Harbor Ops",
      email: "candice.wu@sandbox.dev",
      phone: "+1 (206) 555-0172",
      website: "harborops.com",
      location: "Seattle, WA, USA",
      timezone: "PDT (UTC-7)",
      status: "Lead",
      qualifiedAt: "May 10, 2026",
      tags: ["Data", "Performance"],
    },
    messages: [
      {
        id: 601,
        side: "in",
        text: "The bulk export keeps timing out. It reaches about 60 percent and then throws a gateway error.",
        time: "10:15 AM",
      },
      {
        id: 602,
        side: "out",
        text: "Thanks, Candice. Is this for the full shipment history export or a filtered date range?",
        time: "10:12 AM",
      },
      {
        id: 603,
        side: "in",
        text: "Full history. We need it for a warehouse migration, so the file is pretty large.",
        time: "10:09 AM",
      },
      {
        id: 604,
        side: "out",
        text: "I'll queue it as an async export and email the download link once it finishes. That avoids the gateway timeout.",
        time: "10:06 AM",
      },
    ],
  },
  {
    id: 7,
    group: "Today",
    name: "Natali Craig",
    subject: "Invoice INV-4821 still marked unpaid",
    preview: "Our payment cleared on Friday — screenshot of the confirmation attached here.",
    time: "9:58 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 1,
    contact: {
      name: "Natali Craig",
      role: "Finance Manager",
      company: "Lumen Studio",
      email: "natali.craig@weblabs.studio",
      phone: "+39 02 5555 0184",
      website: "lumenstudio.co",
      location: "Milan, Italy",
      timezone: "CEST (UTC+2)",
      status: "Customer",
      qualifiedAt: "Oct 14, 2025",
      tags: ["Billing", "SMB"],
    },
    messages: [
      {
        id: 701,
        side: "in",
        text: "Invoice INV-4821 still shows unpaid even though our bank transfer cleared last Friday.",
        time: "9:58 AM",
      },
      {
        id: 702,
        side: "out",
        text: "Thanks, Natali. Can you send the transfer reference so I can match it against our payment processor records?",
        time: "9:54 AM",
      },
      {
        id: 703,
        side: "in",
        text: "Just attached the confirmation screenshot. The reference ends in 9147.",
        time: "9:50 AM",
      },
      {
        id: 704,
        side: "out",
        text: "Found it. The payment was received but not reconciled to the invoice. I've marked INV-4821 as paid.",
        time: "9:46 AM",
      },
    ],
  },
  {
    id: 8,
    group: "Today",
    name: "Drew Cano",
    subject: "Onboarding docs for new hire — where to start?",
    preview: "Got a new backend dev starting Monday. Need the standard checklist and repo access steps.",
    time: "9:32 AM",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Drew Cano",
      role: "Engineering Manager",
      company: "AtlasWorks",
      email: "drew.cano@internal.tools",
      phone: "+1 (512) 555-0166",
      website: "atlasworks.co",
      location: "Austin, TX, USA",
      timezone: "CDT (UTC-5)",
      status: "Customer",
      qualifiedAt: "Aug 3, 2025",
      tags: ["Onboarding", "Platform", "NPS Promoter"],
    },
    messages: [
      {
        id: 801,
        side: "in",
        text: "We have a backend developer starting Monday. What's the best onboarding path for repo access and environment setup?",
        time: "9:32 AM",
      },
      {
        id: 802,
        side: "out",
        text: "Hi Drew. I'll send the standard engineering checklist and invite link for the developer workspace.",
        time: "9:28 AM",
      },
      {
        id: 803,
        side: "in",
        text: "Great. Please include staging credentials and any branch naming rules if those are documented.",
        time: "9:24 AM",
      },
      {
        id: 804,
        side: "out",
        text: "Will do. I'll add the staging access request and our repository conventions to the same thread.",
        time: "9:20 AM",
      },
    ],
  },
  {
    id: 9,
    group: "Today",
    name: "Orlando Diggs",
    subject: "Downgrade from Enterprise to Pro plan",
    preview: "We're winding down the project at end of quarter. Is there an early termination fee?",
    time: "9:12 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Orlando Diggs",
      role: "CTO",
      company: "Northstar Workspace",
      email: "orlando.diggs@acme.inc",
      phone: "+1 (720) 555-0195",
      website: "northstarworkspace.com",
      location: "Denver, CO, USA",
      timezone: "MDT (UTC-6)",
      status: "At-Risk",
      qualifiedAt: "Dec 1, 2025",
      tags: ["Churn Risk", "Enterprise", "Downgrade"],
    },
    messages: [
      {
        id: 901,
        side: "in",
        text: "We're winding down the current project and need to downgrade from Enterprise to Pro at the end of the quarter.",
        time: "9:12 AM",
      },
      {
        id: 902,
        side: "out",
        text: "Understood, Orlando. I can walk through the downgrade path and confirm whether any contract terms apply.",
        time: "9:08 AM",
      },
      {
        id: 903,
        side: "in",
        text: "Main question is whether there is an early termination fee or if we can switch at renewal.",
        time: "9:04 AM",
      },
      {
        id: 904,
        side: "out",
        text: "Your agreement allows downgrade at renewal with 30 days notice. I'll send the date and feature impact summary.",
        time: "9:00 AM",
      },
    ],
  },
  {
    id: 10,
    group: "Today",
    name: "Andi Lane",
    subject: "API rate limit hitting hard during peak",
    preview: "Our batch jobs are getting 429s every 15 minutes between 9 and 11 AM. Need a bump.",
    time: "8:47 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 3,
    contact: {
      name: "Andi Lane",
      role: "Backend Lead",
      company: "LedgerLoop",
      email: "andi.lane@weblabs.studio",
      phone: "+353 1 555 0189",
      website: "ledgerloop.io",
      location: "Dublin, Ireland",
      timezone: "IST (UTC+1)",
      status: "Lead",
      qualifiedAt: "Apr 19, 2026",
      tags: ["API", "Scaling", "Enterprise"],
    },
    messages: [
      {
        id: 1001,
        side: "in",
        text: "Our batch jobs are hitting 429s every few minutes during peak hours. We need a temporary rate limit bump.",
        time: "8:47 AM",
      },
      {
        id: 1002,
        side: "out",
        text: "Thanks, Andi. Which API keys are affected and what peak window are you seeing?",
        time: "8:43 AM",
      },
      {
        id: 1003,
        side: "in",
        text: "Mostly invoice-sync and customer-import, between 9 and 11 AM Dublin time.",
        time: "8:39 AM",
      },
      {
        id: 1004,
        side: "out",
        text: "I can raise the limit for those keys for seven days while we review your long-term quota.",
        time: "8:35 AM",
      },
    ],
  },
  {
    id: 11,
    group: "Today",
    name: "Kate Morrison",
    subject: "Custom domain SSL cert expired overnight",
    preview: "Users are seeing certificate warnings when they hit our shop page. This is urgent.",
    time: "8:05 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 6,
    contact: {
      name: "Kate Morrison",
      role: "Product Manager",
      company: "Storefront Labs",
      email: "kate.morrison@weblabs.studio",
      phone: "+1 (213) 555-0192",
      website: "storefrontlabs.com",
      location: "Los Angeles, CA, USA",
      timezone: "PDT (UTC-7)",
      status: "Customer",
      qualifiedAt: "Jun 2, 2026",
      tags: ["Urgent", "SMB", "SSL"],
    },
    messages: [
      {
        id: 1101,
        side: "in",
        text: "Our custom domain started showing certificate warnings overnight. Users cannot complete checkout.",
        time: "8:05 AM",
      },
      {
        id: 1102,
        side: "out",
        text: "Thanks, Kate. I'm checking the certificate renewal job and DNS validation now.",
        time: "8:01 AM",
      },
      {
        id: 1103,
        side: "in",
        text: "DNS has not changed on our side. The warning says the certificate expired at midnight.",
        time: "7:57 AM",
      },
      {
        id: 1104,
        side: "out",
        text: "The renewal job failed on CAA validation. I've reissued the certificate manually and it's propagating.",
        time: "7:53 AM",
      },
    ],
  },
  {
    id: 12,
    group: "Today",
    name: "Alec Whitten",
    subject: "Upgrade to annual billing — is there a discount?",
    preview: "We're ready to commit for the year. Can you send over the annual pricing sheet?",
    time: "7:38 AM",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Alec Whitten",
      role: "Head of IT",
      company: "Crescent Media Group",
      email: "alec.whitten@internal.tools",
      phone: "+974 4455 1234",
      website: "crescentmedia.qa",
      location: "Doha, Qatar",
      timezone: "AST (UTC+3)",
      status: "Qualified",
      qualifiedAt: "May 28, 2026",
      tags: ["Upgrade", "Enterprise", "Media"],
    },
    messages: [
      {
        id: 1201,
        side: "in",
        text: "We're ready to move to annual billing. Is there a discount if we commit for the full year?",
        time: "7:38 AM",
      },
      {
        id: 1202,
        side: "out",
        text: "Hi Alec. Yes, annual billing includes a discount. I can send a quote with the annual terms today.",
        time: "7:34 AM",
      },
      {
        id: 1203,
        side: "in",
        text: "Please include the media team seats and the analytics add-on in the quote.",
        time: "7:30 AM",
      },
      {
        id: 1204,
        side: "out",
        text: "Done. I'll include both and mark the quote for annual prepay so procurement can review it quickly.",
        time: "7:26 AM",
      },
    ],
  },
  {
    id: 13,
    group: "Today",
    name: "Ariana Decker",
    subject: "Bug: date picker off by one in reports",
    preview: "Selecting June 5 produces June 4 in the CSV export. Screenshot attached for reference.",
    time: "6:52 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Ariana Decker",
      role: "QA Analyst",
      company: "Northstar Health",
      email: "ariana.decker@weblabs.studio",
      phone: "+1 (617) 555-0188",
      website: "northstarhealth.com",
      location: "Boston, MA, USA",
      timezone: "EDT (UTC-4)",
      status: "Customer",
      qualifiedAt: "Mar 14, 2026",
      tags: ["Bug", "Reports"],
    },
    messages: [
      {
        id: 1301,
        side: "in",
        text: "The report date picker is off by one. Selecting June 5 exports June 4 in the CSV.",
        time: "6:52 AM",
      },
      {
        id: 1302,
        side: "out",
        text: "Thanks, Ariana. Does the UI show the right date before export, or is it wrong there too?",
        time: "6:48 AM",
      },
      {
        id: 1303,
        side: "in",
        text: "The UI looks correct. Only the CSV output is shifted.",
        time: "6:44 AM",
      },
      {
        id: 1304,
        side: "out",
        text: "That points to timezone conversion in the export job. I'll attach your screenshot to the bug ticket.",
        time: "6:40 AM",
      },
    ],
  },
  {
    id: 14,
    group: "Today",
    name: "Steven Tey",
    subject: "Webhook delivery failures for Zapier integration",
    preview: "Getting intermittent 500s on the webhook endpoint since roughly 2 AM UTC. Logs linked.",
    time: "6:10 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Steven Tey",
      role: "Solutions Architect",
      company: "BridgeWork Inc.",
      email: "steven.tey@sandbox.dev",
      phone: "+1 (404) 555-0141",
      website: "bridgework.io",
      location: "Atlanta, GA, USA",
      timezone: "EDT (UTC-4)",
      status: "Lead",
      qualifiedAt: "Apr 8, 2026",
      tags: ["Integrations", "Platform", "Zapier"],
    },
    messages: [
      {
        id: 1401,
        side: "in",
        text: "Zapier webhook delivery is failing intermittently with 500s. It started around 2 AM UTC.",
        time: "6:10 AM",
      },
      {
        id: 1402,
        side: "out",
        text: "Thanks, Steven. Can you share one failed delivery ID and the endpoint path?",
        time: "6:06 AM",
      },
      {
        id: 1403,
        side: "in",
        text: "Delivery ID wh_72a9. Endpoint is /hooks/zapier/customer-created.",
        time: "6:02 AM",
      },
      {
        id: 1404,
        side: "out",
        text: "I found retries backing up on that endpoint. We're increasing worker capacity and replaying the failed deliveries.",
        time: "5:58 AM",
      },
    ],
  },
  {
    id: 15,
    group: "Today",
    name: "Lori Bryson",
    subject: "Request: granular RBAC for team leads",
    preview: "Our engineering leads need read-only on production but full write access on staging.",
    time: "5:44 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Lori Bryson",
      role: "Platform Architect",
      company: "KumoWorks K.K.",
      email: "lori.bryson@acme.inc",
      phone: "+81 3 5555 0173",
      website: "kumoworks.jp",
      location: "Tokyo, Japan",
      timezone: "JST (UTC+9)",
      status: "Qualified",
      qualifiedAt: "Feb 9, 2026",
      tags: ["RBAC", "Enterprise", "Feature Request"],
    },
    messages: [
      {
        id: 1501,
        side: "in",
        text: "Our team leads need read-only production access but full write permissions in staging. Can RBAC support that split?",
        time: "5:44 AM",
      },
      {
        id: 1502,
        side: "out",
        text: "Yes, Lori. You can separate environment scope from permission level. I'll send the policy example.",
        time: "5:40 AM",
      },
      {
        id: 1503,
        side: "in",
        text: "Great. We also need audit logs to show who changed staging configs.",
        time: "5:36 AM",
      },
      {
        id: 1504,
        side: "out",
        text: "That is included. I'll add the audit log filters to the example so your leads can test it.",
        time: "5:32 AM",
      },
    ],
  },
  {
    id: 16,
    group: "Today",
    name: "Koray Okumus",
    subject: "Mobile app crashes on Android 14 after update",
    preview: "Three users reported the same crash on launch. Stack trace from Firebase attached.",
    time: "5:18 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 3,
    contact: {
      name: "Koray Okumus",
      role: "Mobile Lead",
      company: "MobiSolar Ltd.",
      email: "koray.okumus@weblabs.studio",
      phone: "+254 711 555 0182",
      website: "mobisolar.co.ke",
      location: "Nairobi, Kenya",
      timezone: "EAT (UTC+3)",
      status: "Customer",
      qualifiedAt: "Jan 5, 2026",
      tags: ["Mobile", "Android", "Bug"],
    },
    messages: [
      {
        id: 1601,
        side: "in",
        text: "Our Android users on version 14 are seeing crashes right after the splash screen. Firebase shows three affected devices so far.",
        time: "5:18 AM",
      },
      {
        id: 1602,
        side: "out",
        text: "Thanks for reporting this, Koray. Can you share the Firebase crashlytics link? I'll get the mobile team on it.",
        time: "5:05 AM",
      },
      {
        id: 1603,
        side: "in",
        text: "Sure, linked the stack trace in the ticket. Looks like a null pointer in the payment module init.",
        time: "4:52 AM",
      },
      {
        id: 1604,
        side: "out",
        text: "Found it — there's an edge case when Google Play Services isn't updated. We're pushing a hotfix now.",
        time: "4:40 AM",
      },
    ],
  },
  // Yesterday
  {
    id: 17,
    group: "Yesterday",
    name: "Josh Miller",
    subject: "Partnership proposal for Latin American market",
    preview: "We're expanding into Mexico and Brazil next quarter. Would love to explore a reseller deal.",
    time: "Yesterday",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Josh Miller",
      role: "CEO",
      company: "Nexo Digital MX",
      email: "josh.miller@internal.tools",
      phone: "+52 55 5555 0165",
      website: "nexodigital.mx",
      location: "Mexico City, Mexico",
      timezone: "CST (UTC-6)",
      status: "Lead",
      qualifiedAt: "May 15, 2026",
      tags: ["Partnership", "LATAM", "Reseller"],
    },
    messages: [
      {
        id: 1701,
        side: "in",
        text: "We're expanding into Mexico and Brazil next quarter and want to explore a reseller partnership.",
        time: "Yesterday",
      },
      {
        id: 1702,
        side: "out",
        text: "Thanks, Josh. That sounds aligned with our LATAM plans. Do you already have target customer segments in mind?",
        time: "Yesterday",
      },
      {
        id: 1703,
        side: "in",
        text: "Mostly mid-market logistics and retail teams. We can bring initial pipeline if the reseller terms work.",
        time: "Yesterday",
      },
      {
        id: 1704,
        side: "out",
        text: "I'll introduce you to our partnerships lead and share the reseller tier overview before Friday.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 18,
    group: "Yesterday",
    name: "Mollie Hall",
    subject: "Data export — need all logs from May",
    preview: "Our compliance audit starts next week. I need a full activity log dump for the auditors.",
    time: "Yesterday",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Mollie Hall",
      role: "Compliance Officer",
      company: "NovaPay Ltd.",
      email: "mollie.hall@weblabs.studio",
      phone: "+44 20 5555 0178",
      website: "novapay.co.uk",
      location: "London, UK",
      timezone: "BST (UTC+1)",
      status: "Customer",
      qualifiedAt: "Nov 8, 2025",
      tags: ["Compliance", "FinServ", "Audit"],
    },
    messages: [
      {
        id: 1801,
        side: "in",
        text: "Our compliance audit starts next week. We need activity logs for all May workspace events.",
        time: "Yesterday",
      },
      {
        id: 1802,
        side: "out",
        text: "Hi Mollie. We can export admin activity, login events, and file access logs. Do auditors need CSV or JSON?",
        time: "Yesterday",
      },
      {
        id: 1803,
        side: "in",
        text: "CSV is fine, but it needs user IDs and timestamps in UTC.",
        time: "Yesterday",
      },
      {
        id: 1804,
        side: "out",
        text: "Understood. I'll prepare the May export with UTC timestamps and send it through the secure file link.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 19,
    group: "Yesterday",
    name: "Rene Wells",
    subject: "White-label options for our reseller program",
    preview: "We have five partners asking about branded dashboards. Do you offer white-label tiers?",
    time: "Yesterday",
    isUnread: true,
    isOnline: true,
    unreadCount: 1,
    contact: {
      name: "Rene Wells",
      role: "Product Director",
      company: "Jambo Digital KE",
      email: "rene.wells@acme.inc",
      phone: "+254 722 555 0194",
      website: "jambodigital.ke",
      location: "Nairobi, Kenya",
      timezone: "EAT (UTC+3)",
      status: "Qualified",
      qualifiedAt: "Apr 25, 2026",
      tags: ["White-Label", "Reseller", "Platform"],
    },
    messages: [
      {
        id: 1901,
        side: "in",
        text: "We have five reseller partners asking whether the dashboard can be white-labeled.",
        time: "Yesterday",
      },
      {
        id: 1902,
        side: "out",
        text: "Hi Rene. White-labeling is available on the partner tier. Are they asking about custom domain, logo, or full theme control?",
        time: "Yesterday",
      },
      {
        id: 1903,
        side: "in",
        text: "All three, ideally. They want their own domain and branded reports for clients.",
        time: "Yesterday",
      },
      {
        id: 1904,
        side: "out",
        text: "That is supported. I'll send the partner tier doc and a sample branded report template.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 20,
    group: "Yesterday",
    name: "Rylee Howard",
    subject: "MFA enforcement rollout — questions",
    preview: "Our security team wants to know if SMS fallback is still supported after the enforcement date.",
    time: "Yesterday",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Rylee Howard",
      role: "Security Architect",
      company: "Grupo Financiero Sur",
      email: "rylee.howard@sandbox.dev",
      phone: "+57 601 555 0180",
      website: "gfsur.com.co",
      location: "Bogotá, Colombia",
      timezone: "COT (UTC-5)",
      status: "Qualified",
      qualifiedAt: "Mar 30, 2026",
      tags: ["Security", "Enterprise", "MFA"],
    },
    messages: [
      {
        id: 2001,
        side: "in",
        text: "Our security team has questions about the MFA enforcement rollout. Is SMS fallback still supported?",
        time: "Yesterday",
      },
      {
        id: 2002,
        side: "out",
        text: "Hi Rylee. SMS fallback remains available, but we recommend authenticator apps or security keys for admins.",
        time: "Yesterday",
      },
      {
        id: 2003,
        side: "in",
        text: "Can we enforce security keys for admins and allow SMS only for contractors?",
        time: "Yesterday",
      },
      {
        id: 2004,
        side: "out",
        text: "Yes. You can configure that by user group. I'll send the policy setup steps.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 21,
    group: "Yesterday",
    name: "Sienna Hewitt",
    subject: "Missing line items in CSV export",
    preview: "The January invoice export is short by three line items. The PDF version is correct though.",
    time: "Yesterday",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Sienna Hewitt",
      role: "Finance Director",
      company: "Volta Energy AB",
      email: "sienna.hewitt@weblabs.studio",
      phone: "+46 73 555 0168",
      website: "voltaenergy.se",
      location: "Malmö, Sweden",
      timezone: "CEST (UTC+2)",
      status: "Customer",
      qualifiedAt: "Sep 12, 2025",
      tags: ["Billing", "Export", "Bug"],
    },
    messages: [
      {
        id: 2101,
        side: "in",
        text: "The January invoice CSV is missing three line items. The PDF invoice looks correct.",
        time: "Yesterday",
      },
      {
        id: 2102,
        side: "out",
        text: "Thanks, Sienna. Are the missing line items discounts, usage charges, or taxes?",
        time: "Yesterday",
      },
      {
        id: 2103,
        side: "in",
        text: "Two are usage charges and one is a tax adjustment. They all appear in the PDF.",
        time: "Yesterday",
      },
      {
        id: 2104,
        side: "out",
        text: "I found an export filter excluding adjusted usage lines. We'll patch it and regenerate the January CSV for you.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 22,
    group: "Yesterday",
    name: "Noah Pierre",
    subject: "Demo request for procurement team — Friday",
    preview: "Need a 30-minute walkthrough of the vendor portal for our finance leads this Friday.",
    time: "Yesterday",
    isUnread: true,
    isOnline: false,
    unreadCount: 5,
    contact: {
      name: "Noah Pierre",
      role: "Procurement Manager",
      company: "First Atlantic Bank NG",
      email: "noah.pierre@weblabs.studio",
      phone: "+234 805 555 0125",
      website: "firstatlanticbank.ng",
      location: "Abuja, Nigeria",
      timezone: "WAT (UTC+1)",
      status: "Lead",
      qualifiedAt: "May 20, 2026",
      tags: ["Demo", "FinServ", "Enterprise"],
    },
    messages: [
      {
        id: 2201,
        side: "in",
        text: "Could we schedule a 30-minute demo for our procurement and finance leads this Friday?",
        time: "Yesterday",
      },
      {
        id: 2202,
        side: "out",
        text: "Absolutely, Noah. Should the walkthrough focus on vendor onboarding, approvals, or reporting?",
        time: "Yesterday",
      },
      {
        id: 2203,
        side: "in",
        text: "Vendor onboarding and approval routing are the priority. Reporting can be a quick overview.",
        time: "Yesterday",
      },
      {
        id: 2204,
        side: "out",
        text: "Great. I'll send a Friday slot with an agenda tailored to those two workflows.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 23,
    group: "Yesterday",
    name: "Eve Lechner",
    subject: "SSO integration with Azure AD",
    preview: "We're migrating from Okta to Azure AD. What's the typical setup timeline for SSO?",
    time: "Yesterday",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Eve Lechner",
      role: "IT Director",
      company: "Northlane IT",
      email: "eve.lechner@acme.inc",
      phone: "+420 222 555 013",
      website: "northlaneit.com",
      location: "Prague, Czechia",
      timezone: "CEST (UTC+2)",
      status: "Qualified",
      qualifiedAt: "Feb 14, 2026",
      tags: ["SSO", "Azure", "Enterprise"],
    },
    messages: [
      {
        id: 2301,
        side: "in",
        text: "We're moving from Okta to Azure AD and need to understand the SSO setup timeline.",
        time: "Yesterday",
      },
      {
        id: 2302,
        side: "out",
        text: "Hi Eve. Typical Azure AD SSO setup takes one to two business days once metadata is exchanged.",
        time: "Yesterday",
      },
      {
        id: 2303,
        side: "in",
        text: "We can share metadata today. Will there be downtime during the switch?",
        time: "Yesterday",
      },
      {
        id: 2304,
        side: "out",
        text: "No downtime if we test with a pilot group first. I'll send the Azure AD checklist and rollout plan.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 24,
    group: "Yesterday",
    name: "Zahir McClure",
    subject: "Cancellation request — account owner left",
    preview: "Our ops lead resigned last week. Need to transfer ownership to me before we can cancel.",
    time: "Yesterday",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Zahir McClure",
      role: "Operations Director",
      company: "Cedar Grove Ventures",
      email: "zahir.mcclure@internal.tools",
      phone: "+1 (615) 555-0175",
      website: "cedargrove.vc",
      location: "Nashville, TN, USA",
      timezone: "CDT (UTC-5)",
      status: "At-Risk",
      qualifiedAt: "Jun 15, 2025",
      tags: ["Churn Risk", "Account", "SMB"],
    },
    messages: [
      {
        id: 2401,
        side: "in",
        text: "Our ops lead Jamal resigned last week and he was the only account owner. I need ownership transferred to me before we can proceed with anything.",
        time: "Yesterday",
      },
      {
        id: 2402,
        side: "out",
        text: "Hi Zahir, I can help with that. We'll need verification — can you confirm your role and provide a copy of Jamal's resignation notice?",
        time: "Yesterday",
      },
      {
        id: 2403,
        side: "in",
        text: "Absolutely. I'm the Operations Director. I've attached his signed notice and HR confirmation.",
        time: "Yesterday",
      },
      {
        id: 2404,
        side: "out",
        text: "Verified. I've initiated the ownership transfer. It takes about 2 hours to propagate. You'll get a confirmation email once it's done.",
        time: "Yesterday",
      },
    ],
  },
];

export const currentUser = {
  name: "Arham Khan",
  email: "arham.khan@weblabs.studio",
};
