name: Build Go Binaries For Verification

on:
  workflow_call:
    inputs:
      go_version:
        required: true
        type: string
      ubuntu_version:
        required: true
        type: string
      build_artifact_name:
        required: true
        type: string
    
    outputs:
      build_artifact_name:
        description: "Name of uploaded artifacts"
        value: ${{ inputs.build_artifact_name }}

jobs:
  build:
    runs-on: ubuntu-${{ inputs.ubuntu_version }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # @v3
      with:
        fetch-depth: 0
  
    - name: Build
      uses: ./.github/actions/go-build
      with:
        go_version: ${{ inputs.go_version }}
        working_directory: .

    - name: Upload build
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # @v4
      with:
        name: ${{ inputs.build_artifact_name }}
        path: avalanchego/build/